# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloudtext',
            name='link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Original URL'),
        ),
    ]
