# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Tags')),
                ('timestamp', models.DateTimeField(verbose_name='Time')),
                ('candidate_tag', models.ManyToManyField(related_name='timeline_news', to='candidate.Candidate', verbose_name="Candidates' tag")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='blog.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
