# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='breaking',
            field=models.BooleanField(default=False),
        ),
    ]
