# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20170103_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Image Caption'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'candidate/logos', verbose_name='Image'),
        ),
    ]
