# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('text', models.CharField(max_length=128, verbose_name='Text')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Order')),
                ('value', models.IntegerField(verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('unset', 'Unset'), ('male', 'male'), ('female', 'female')], default='unset', max_length=8, null=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Question Text')),
                ('extra', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Extra Information')),
                ('qtype', models.CharField(choices=[('MCH', 'Multiple Choice'), ('PER', 'Percentage'), ('TXT', 'Text')], max_length=3, verbose_name='Question Type')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('required', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Order')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='questionnaire.Questionnaire', verbose_name='Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(verbose_name='Answer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='questionnaire.Participant', verbose_name='Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='questionnaire.Question', verbose_name='Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionnaire.QuestionSet', verbose_name='Question Set'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('question', 'participant')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('order', 'question_set')]),
        ),
    ]
