# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20170322_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.ChoiceSet', verbose_name='Choise Set'),
            preserve_default=False,
        ),
    ]
