# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20170322_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionnaire.ChoiceSet', verbose_name='Choice Set'),
            preserve_default=False,
        ),
    ]
