# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20170323_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.IntegerField(verbose_name='Answer'),
        ),
    ]
