# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 16:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20170323_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='extra',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Extra Information'),
        ),
    ]
