# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='homepage_feature',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='candidate_tag',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='candidate.Candidate', verbose_name="Candidates' tag"),
        ),
    ]
