# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 22:53
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161229_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, verbose_name='Comment Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='Published Time'),
        ),
    ]
