# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170103_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'blog/images', verbose_name='Feature Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='feature_image_caption',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
