# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170104_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
