# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:24
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Tags')),
                ('last_name', models.CharField(max_length=512, verbose_name='Last Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'candidate/photos', verbose_name='Photo')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography')),
                ('history', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Polictical History')),
                ('platform', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Platform')),
                ('website', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Website')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=512, null=True, verbose_name='Telephone')),
                ('fax', models.CharField(blank=True, max_length=512, null=True, verbose_name='Fax')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter', models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter Handle')),
                ('instagram', models.CharField(blank=True, max_length=128, null=True, verbose_name='Instagram Handle')),
                ('telegram', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram Handle')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('status_text', models.CharField(blank=True, max_length=512, null=True, verbose_name='Status Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Tags')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'candidate/logos', verbose_name='Logo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link URL')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ManyToManyField(related_name='candidate', to='candidate.Party', verbose_name='Party'),
        ),
    ]
