# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 21:13
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Order')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Tags')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'candidate/logos', verbose_name='Photo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Order')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('tag', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssuesStance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('stance', models.TextField(blank=True, null=True, verbose_name='Stance on Issue')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='history',
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_place',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='military_background',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Military Background'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='political_background',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Polictical Background'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='political_orientation',
            field=models.TextField(blank=True, null=True, verbose_name='Political Orientation'),
        ),
        migrations.AddField(
            model_name='party',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography Summary'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ManyToManyField(related_name='candidate', to='candidate.Party', verbose_name='Supporting Parties'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'candidate/photos', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='issuesstance',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='issuesstance',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Issue', verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='figure',
            field=models.ManyToManyField(related_name='candidate', to='candidate.Figure', verbose_name='Supporting Figures'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='issue',
            field=models.ManyToManyField(through='candidate.IssuesStance', to='candidate.Issue'),
        ),
    ]
