# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 20:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20161220_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figure',
            options={'verbose_name_plural': 'Political Figures'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Polictical Parties'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='figure',
            field=models.ManyToManyField(blank=True, related_name='candidate', to='candidate.Figure', verbose_name='Supporting Figures'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ManyToManyField(blank=True, related_name='candidate', to='candidate.Party', verbose_name='Supporting Parties'),
        ),
    ]
