# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20170405_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
