# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20170405_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('-status', 'last_name')},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'Issue Categories'},
        ),
        migrations.AlterModelOptions(
            name='issuesstance',
            options={'ordering': ('issue__order',)},
        ),
    ]
